import 'package:flutter/material.dart';
import 'package:flutter/services.dart'; // Required for SystemNavigator.pop()
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_app_check/firebase_app_check.dart';
import 'package:flutter/foundation.dart'; // REQUIRED for kIsWeb
import 'firebase_options.dart'; // Generated by 'flutterfire configure'

import 'package:google_fonts/google_fonts.dart';

// Screens
import 'screens/login_screen.dart';
import 'screens/student/student_dashboard.dart';
import 'screens/admin/admin_dashboard.dart';
import 'screens/staff/staff_dashboard.dart';
import 'screens/cert_verify_screen.dart';

// Services
import 'services/notification_service.dart';
import 'services/activity_tracker.dart';
import 'services/auth_service.dart';
import 'screens/splash_screen.dart';
import 'theme/app_colors.dart';

// Global Key for ScaffoldMessenger to show notifications from anywhere
final GlobalKey<ScaffoldMessengerState> messengerKey = GlobalKey<ScaffoldMessengerState>();
// Global Key for Navigator to perform navigation from anywhere
final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Firebase with error handling
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );

    // FIX: Initialize App Check only where supported or configured
    if (!kIsWeb) {
      await FirebaseAppCheck.instance.activate(
        androidProvider: AndroidProvider.debug,
        appleProvider: AppleProvider.deviceCheck,
      );
    } else {
      // For Web, App Check requires a ReCaptcha site key. 
      // Skipping for now to allow development on Chrome.
      print("Firebase App Check: Skipping activation on Web (requires ReCaptcha config).");
    }
    
    // Initialize notification service
    await NotificationService().initialize();
    
    // Initialize activity tracker
    ActivityTracker().initialize();
    
    // Ensure Master Admin Exists (Seeding)
    await AuthService().ensureMasterAdminExists();
    
  } catch (e, stack) {
    print("Firebase Initialization Error: $e");
    print("Stack Trace: $stack");
  }

  runApp(const ADACSApp());
}

class ADACSApp extends StatefulWidget {
  const ADACSApp({super.key});

  @override
  State<ADACSApp> createState() => _ADACSAppState();
}

class _ADACSAppState extends State<ADACSApp> with WidgetsBindingObserver {
  // Professional Red Color matching your dashboards
  final Color customRed = const Color.fromARGB(255, 198, 55, 45);

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    // Update badge count on app launch
    Future.delayed(const Duration(seconds: 2), () async {
      await NotificationService().updateAppBadge();
      await NotificationService().showLaunchNotification();
    });
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.resumed) {
      NotificationService().updateAppBadge();
      NotificationService().showLaunchNotification();
    }
  }

  // Global Exit Confirmation Dialog
  Future<bool> _showExitDialog(BuildContext context) async {
    return await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(24)),
        title: const Text("Exit Application", style: TextStyle(color: AppColors.red, fontWeight: FontWeight.bold)),
        content: const Text("Are you sure you want to close the app?"),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(context).pop(false),
            child: const Text("Cancel", style: TextStyle(color: Colors.grey)),
          ),
          ElevatedButton(
            style: ElevatedButton.styleFrom(backgroundColor: AppColors.red),
            onPressed: () => Navigator.of(context).pop(true),
            child: const Text("Exit"),
          ),
        ],
      ),
    ) ?? false;
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'A-DACS',
      debugShowCheckedModeBanner: false,
      navigatorKey: navigatorKey,
      scaffoldMessengerKey: messengerKey,
      theme: ThemeData(
        useMaterial3: true,
        primaryColor: AppColors.red,
        // Premium Institutional Typography
        textTheme: GoogleFonts.outfitTextTheme(),
        colorScheme: ColorScheme.fromSeed(
          seedColor: AppColors.red,
          primary: AppColors.red,
          secondary: AppColors.slate,
          surface: AppColors.surface,
          background: AppColors.background,
        ),
        scaffoldBackgroundColor: AppColors.background,
        
        // Premium Dialog Theme (Global 24px)
        dialogTheme: DialogThemeData(
          backgroundColor: AppColors.surface,
          elevation: 10,
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(24)),
          titleTextStyle: GoogleFonts.outfit(
            color: AppColors.slate,
            fontSize: 22,
            fontWeight: FontWeight.bold,
          ),
          contentTextStyle: GoogleFonts.outfit(
            color: AppColors.slateLight,
            fontSize: 15,
          ),
        ),

        // Floating SnackBar Theme
        snackBarTheme: SnackBarThemeData(
          behavior: SnackBarBehavior.floating,
          backgroundColor: AppColors.slate,
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
          contentTextStyle: GoogleFonts.outfit(color: Colors.white),
        ),

        // Card Theme (Global 24px)
        cardTheme: CardThemeData(
          color: AppColors.surface,
          elevation: 0,
          margin: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(24),
            side: BorderSide(color: AppColors.slateLighter.withOpacity(0.5)),
          ),
        ),

        appBarTheme: const AppBarTheme(
          backgroundColor: AppColors.background,
          foregroundColor: AppColors.slate,
          centerTitle: true,
          elevation: 0,
        ),

        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: AppColors.red,
            foregroundColor: Colors.white,
            padding: const EdgeInsets.symmetric(horizontal: 28, vertical: 16),
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
            elevation: 0,
            textStyle: GoogleFonts.outfit(
              fontWeight: FontWeight.bold,
              fontSize: 15,
              letterSpacing: 0.5
            ),
          ),
        ),

        outlinedButtonTheme: OutlinedButtonThemeData(
          style: OutlinedButton.styleFrom(
            foregroundColor: AppColors.red,
            side: const BorderSide(color: AppColors.red, width: 1.5),
            padding: const EdgeInsets.symmetric(horizontal: 28, vertical: 16),
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
          ),
        ),

        inputDecorationTheme: InputDecorationTheme(
          filled: true,
          fillColor: AppColors.surface,
          border: OutlineInputBorder(borderRadius: BorderRadius.circular(16)),
          contentPadding: const EdgeInsets.symmetric(horizontal: 20, vertical: 18),
          labelStyle: GoogleFonts.outfit(color: AppColors.slateLight),
          hintStyle: GoogleFonts.outfit(color: AppColors.grey),
          enabledBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(16),
            borderSide: BorderSide(color: AppColors.slateLighter.withOpacity(0.8)),
          ),
          focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(16),
            borderSide: const BorderSide(color: AppColors.red, width: 2),
          ),
        ),
      ),
      // Use PopScope globally to handle Exit Confirmation
      home: PopScope(
        canPop: false,
        onPopInvokedWithResult: (didPop, result) async {
          if (didPop) return;
          
          final NavigatorState? nav = navigatorKey.currentState;
          if (nav != null && nav.canPop()) {
            nav.pop(); // Go back if there's a previous screen in history
          } else {
            // At root screen, show exit confirmation
            final shouldExit = await _showExitDialog(context);
            if (shouldExit) {
              SystemNavigator.pop(); // Close the app
            }
          }
        },
        child: const SplashScreen(),
      ),
      onGenerateRoute: (settings) {
        final uri = Uri.tryParse(settings.name ?? '');
        if (uri != null && uri.path == '/verify') {
          final certId = uri.queryParameters['id'] ?? '';
          return MaterialPageRoute(
            builder: (_) => CertVerifyScreen(certId: certId),
            settings: settings,
          );
        }
        return null;
      },
    );
  }
}

/// This widget listens to the Auth State (Logged In vs Logged Out)
class AuthWrapper extends StatelessWidget {
  const AuthWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(body: Center(child: CircularProgressIndicator()));
        }

        if (snapshot.hasData && snapshot.data != null) {
          return const RoleResolver();
        }

        return const LoginScreen();
      },
    );
  }
}

/// Fetches the User's Role from Firestore to decide which Dashboard to show
class RoleResolver extends StatelessWidget {
  const RoleResolver({super.key});

  @override
  Widget build(BuildContext context) {
    final User user = FirebaseAuth.instance.currentUser!;

    return FutureBuilder<DocumentSnapshot>(
      future: FirebaseFirestore.instance.collection('users').doc(user.uid).get(),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            body: Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  CircularProgressIndicator(),
                  SizedBox(height: 20),
                  Text("Fetching Profile..."),
                ],
              ),
            ),
          );
        }

        if (snapshot.hasError || !snapshot.hasData || !snapshot.data!.exists) {
          return Scaffold(
            body: Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  const Icon(Icons.lock_person_outlined, size: 60, color: Colors.red),
                  const SizedBox(height: 16),
                  const Padding(
                    padding: EdgeInsets.symmetric(horizontal: 40, vertical: 8),
                    child: Text(
                      "Please ensure your account is approved and Firestore rules allow access.",
                      textAlign: TextAlign.center,
                    ),
                  ),
                  const Text(
                    "A-DACS",
                    style: TextStyle(
                      fontSize: 28,
                      fontWeight: FontWeight.bold,
                      color: Color.fromARGB(255, 198, 55, 45), // CHANGED: Red Title
                      letterSpacing: 2,
                    ),
                  ),
                  const Text(
                    "Digital Clearance System",
                    style: TextStyle(fontSize: 14, color: Colors.grey),
                  ),
                  const SizedBox(height: 40),
                  TextButton(
                    onPressed: () => FirebaseAuth.instance.signOut(), 
                    child: const Text("Logout & Try Again")
                  ),
                ],
              ),
            ),
          );
        }

        final data = snapshot.data!.data() as Map<String, dynamic>;
        final String role = data['role'] ?? 'student';

        NotificationService().updateAppBadge();

        if (role == 'admin') {
          return const AdminDashboard();
        } else if (role == 'staff') {
          return const StaffDashboard();
        } else {
          return const StudentDashboard();
        }
      },
    );
  }
}